name: Rails CI/CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Deploy
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        USER_NAME: ${{ secrets.USER_NAME }}
        HOST_NAME: ${{ secrets.HOST_NAME }}
      run: |
      echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
      ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOST_NAME} 'cd kicklog &&
      git pull origin main &&
      ~/.rbenv/shims/bundle install &&
      ~/.rbenv/shims/bundle exec rails assets:precompile RAILS_ENV=production &&
      ~/.rbenv/shims/bundle exec rails db:migrate RAILS_ENV=production &&
      rm -f tmp/pids/puma.pid && rm -f tmp/sockets/puma.sock &&
      ~/.rbenv/shims/rails s -e production -d'